### ISSUE TITLE
Collision Detection for Placing Subjects doesnt Work in current dev Version

### ISSUE THREAD

**Issue by derstaubige** [derstaubige/jTimetable#2]
When generating an Timetable, it doesnt Consider that Lecturer are ocupied in other Timetable
![image](https://user-images.githubusercontent.com/61210083/221175779-c4c0039c-47e6-4c85-a4ca-0da73d884ac4.png)

Even if i drag and drop subjects arround, they are shown as free / green

![image](https://user-images.githubusercontent.com/61210083/221176090-ebe1ad63-1572-47a3-af45-9f07944a4841.png)

**Comment by BlackDiamondWing** [comment]
Update:
The Blocked Recources aren't stored correctly in Database, because the Method resourcessBlocked.save() is never executed. I don't know why yet.

**Comment by BlackDiamondWing** [comment]
The Blocked Resources are stored correctly, but resources were blocked more than once because there was a mistake in select command which checks whether the resource is free.
Double stored:
![image](https://user-images.githubusercontent.com/105712615/221831734-1f514e49-0bd0-4199-9067-c8d71bee034f.png)
Copy SQL Statement from code:
![image](https://user-images.githubusercontent.com/105712615/221831899-35858a34-78c9-4034-b1f3-2b7f9bd08975.png)

Solution:
LECTURER needs to be written in capital letters to find the database entries.

Following Problem:
Issue 4: Blocked Resources aren't displayed correctly in theyre timetable
